package im.tox.tox4j.crypto

object ToxCryptoConstants {

  /** Length of salt in bytes. */
  const val SaltLength = 32

  /**
   * The number of bytes in a serialised [[ToxCrypto.PassKey]] without salt. The serialised size is
   * [[KeyLength]] + [[SaltLength]].
   */
  const val KeyLength = 32

  /** Number of bytes added to any encrypted data. */
  const val EncryptionExtraLength = 80

  /** The number of bytes in a hash generated by tox_hash. */
  const val HashLength = 32

  const val PublicKeyLength = 32
  const val SecretKeyLength = 32
  const val SharedKeyLength = 32
  const val NonceLength = 24

  const val ZeroBytes = 32
  const val BoxZeroBytes = 16
}
