---
_extends: .github

repository:
  name: jvm-toxcore-c
  description: JVM (Java/Scala/Kotlin) bindings to toxcore
  topics: tox, java, scala, toxcore
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - bazel-opt
          - Codacy Static Code Analysis
          - code-review/reviewable
