---
_extends: template

repository:
  name: jvm-toxcore-c
  description: JVM (Java/Scala/Kotlin) bindings to toxcore
  topics: tox, java, scala, toxcore
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Codefactor
          - Travis CI - Pull Request
          - WIP
          - code-review/reviewable
          - coverage/coveralls
          - license/cla
