---
bazel-opt_task:
  container:
    image: toxchat/toktok-stack:latest-release
    cpu: 2
    memory: 6G
  configure_script:
    - /src/workspace/tools/inject-repo jvm-toxcore-c
  test_all_script:
    - cd /src/workspace && bazel test -k //jvm-toxcore-c/...
