package im.tox.tox4j.crypto

object ToxCryptoConstants {
    /** Length of salt in bytes. */
    const val SALT_LENGTH = 32

    /**
     * The number of bytes in a serialised [[ToxCrypto.PassKey]] without salt. The serialised size
     * is [[KEY_LENGTH]] + [[SALT_LENGTH]].
     */
    const val KEY_LENGTH = 32

    /** Number of bytes added to any encrypted data. */
    const val ENCRYPTION_EXTRA_LENGTH = 80

    /** The number of bytes in a hash generated by tox_hash. */
    const val HASH_LENGTH = 32

    const val PUBLIC_KEY_LENGTH = 32
    const val SECRET_KEY_LENGTH = 32
    const val SHARED_KEY_LENGTH = 32
    const val NONCE_LENGTH = 24

    const val ZERO_BYTES = 32
    const val BOX_ZERO_BYTES = 16
}
