#!/usr/bin/env perl

use strict;
use utf8;
use lib 'buildscripts';

use Data::Dumper;

use BuildScript;
my $C = require C;


##############################################################################
#
# :: Run "sbt proguard:proguard" on tox4j.
#
##############################################################################

pushd {
   must_system "sbt", "proguard:proguard";
} "projects/tox4j";
