#!/usr/bin/env perl

use strict;
use utf8;
use lib 'buildscripts';

use Data::Dumper;

use BuildScript;
my $C = require C;


##############################################################################
#
# :: Upload artifacts to online file sharing service.
#
##############################################################################


for (<projects/tox4j/target/cpp/bin/*>) {
   print "Uploading $_ to uguu.se...\n";
   my @lines = must_popen (
      "curl", "-s", "-i", "-F", "file=\@$_", "https://uguu.se/api.php?d=upload-tool"
   );
   print "File uploaded to ", (pop @lines), "\n";
}
