#!/usr/bin/env perl

use strict;
use utf8;
use lib 'buildscripts';

use Data::Dumper;
use File::Path 'remove_tree';

use BuildScript;
my $C = require C;


##############################################################################
#
# :: Upload artifacts to online file sharing service.
#
##############################################################################


my $M2DIR = "$ENV{HOME}/.m2/repository/im";
my $REPODIR = 'repositories/snapshots/im';
my $GITHUB_KEY = $C->GITHUB_KEY;


for (<projects/tox4j/target/cpp/bin/*>) {
   print "Uploading $_ to uguu.se...\n";
   my @lines = must_popen (
      "curl", "-s", "-i", "-F", "file=\@$_", "https://uguu.se/api.php?d=upload-tool"
   );
   print "File uploaded to ", (pop @lines), "\n";
}


#if ($GITHUB_KEY and -d $M2DIR and $C->GOAL eq 'coverage') {
if ($GITHUB_KEY and -d $M2DIR) {
   my $repo = "tox4j.github.io";
   print "Publishing artifacts to $repo...\n";

   must_system "git", "config", "--global", "push.default", "simple";
   must_system "git", "config", "--global", "user.email", 'tox4j@travis-ci.org';
   must_system "git", "config", "--global", "user.name", 'Travis CI Snapshot Uploader';

   # Don't use must_system, because that prints its arguments.
   if (not -d $repo) {
      (system "git", "clone", "https://$GITHUB_KEY\@github.com/tox4j/$repo")
         == 0 or die "Could not clone snapshots repository";
   }

   pushd {
      remove_tree $REPODIR;
      must_system "cp", "-a", $M2DIR, $REPODIR;
      must_system "git", "add", "-A", ".";
      must_system "git", "commit", "-a", "--amend", "-mPublished snapshot at " . gmtime;
      must_system "git", "push", "--force", "-q";
   } $repo;
}
