#!/usr/bin/env perl

use strict;
use utf8;
use lib 'buildscripts';

use Cwd 'abs_path';
use Data::Dumper;
use File::Path 'make_path', 'remove_tree';

use BuildScript;
my $C = require C;


##############################################################################
#
# :: Upload artifacts to online file sharing service.
#
##############################################################################


my $M2DIR = "$ENV{HOME}/.m2/repository/im";
my $REPODIR = 'repositories/snapshots/im';
my $GITHUB_KEY = $C->GITHUB_KEY;

# Upload artifacts if the build was not a test build. Test builds instrument
# the code to gather coverage information. We don't want that instrumentation
# to end up in production builds.
if ($GITHUB_KEY and -d $M2DIR and not $C->TEST_GOAL) {
   my $repo = "tox4j.github.io";
   print "Publishing artifacts to $repo...\n";

   # Don't use must_system, because that prints its arguments.
   if (not -d $repo) {
      (system "git", "clone", "https://$GITHUB_KEY\@github.com/tox4j/$repo")
         == 0 or die "Could not clone snapshots repository";
   }

   my @libraries = map { abs_path $_ } <projects/tox4j/target/cpp/bin/*>;

   pushd {
      if (@libraries) {
         my $LIBDIR = 'native/' . $C->TARGET;
         make_path $LIBDIR;
         must_system "cp", @libraries, $LIBDIR;
      }

      remove_tree $REPODIR;
      must_system "cp", "-a", $M2DIR, $REPODIR;

      must_system "git", "config", "push.default", "simple";
      must_system "git", "config", "user.email", 'tox4j@travis-ci.org';
      must_system "git", "config", "user.name", 'Travis CI Snapshot Uploader';

      must_system "git", "add", "-A", ".";
      must_system "git", "commit", "-a", "--amend", "-mPublished snapshot at " . gmtime;
      must_system "git", "push", "--force", "-q";
   } $repo;
}
