#!/usr/bin/env perl

use strict;
use utf8;
use lib 'buildscripts';

use BuildScript;
my $C = require C;


##############################################################################
#
# :: Upload artifacts to online file sharing service.
#
##############################################################################


# Hack to make sbt-coveralls work with our non-standard directory layout.
must_system 'ln -s $PWD/.git projects/';
#must_system 'ln -s $PWD/projects/tox4j/src/main/java/* $PWD/projects/tox4j/';

if ($C->TEST_GOAL eq "coverage" and -f "projects/tox4j/target/scala-2.11/coverage-report/cobertura.xml") {
   pushd {
      must_system $C->SBT, "coverageAggregate", "coveralls";
   } "projects";
}
