#!/usr/bin/env perl

use strict;
use utf8;
use lib 'buildscripts';

use BuildScript;
my $C = require C;


##############################################################################
#
# :: Submit coverage report to coveralls.
#
##############################################################################


# Hack to make sbt-coveralls work.
must_system "cp -r \$PWD/src/main/*/* \$PWD/";

if ($C->TEST_GOAL eq "coverage" and -f "target/scala-2.11/coverage-report/cobertura.xml") {
   must_system $C->SBT, "coveralls";
}
