#!/usr/bin/env perl

use strict;
use utf8;
use lib 'buildscripts';

use BuildScript;
my $C = require C;


##############################################################################
#
# :: Upload artifacts to online file sharing service.
#
##############################################################################


# Hack to make sbt-coveralls work with our non-standard directory layout.
must_system 'ln -s $PWD/.git projects/';
for (qw/linters macros sbt-plugins tox4j/) {
   must_system "cp -r \$PWD/projects/$_/src/main/*/* \$PWD/projects/";
}

if ($C->TEST_GOAL eq "coverage" and -f "projects/tox4j/target/scala-2.11/coverage-report/cobertura.xml") {
   pushd {
      must_system $C->SBT, "coverageAggregate", "coveralls";
   } "projects";
}
