#!/bin/sh

set -x

export TEST_GOAL=proguard
export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64
export PATH=$CACHE_DIR/usr/bin:$PATH

buildscripts/00_dependencies_host

export CC=$CACHE_DIR/usr/bin/clang
export CXX=$CACHE_DIR/usr/bin/clang++

# If the above setup step did its job, start the build.
if which sbt && which clang; then
  buildscripts/04_build
fi

# Copy the native library and the final minified jar to cache.
mkdir -p $CACHE_DIR/binaries

if [ -d target/x86_64-linux ]; then
  mv target/x86_64-linux/*.so $CACHE_DIR/binaries
  mv target/scala-2.11/proguard/tox4j_2.11-0.1-SNAPSHOT.jar $CACHE_DIR/binaries
fi

# Copy them back if they were updated.
cp $CACHE_DIR/binaries/* .

# Delete everything else.
rm -rf */
