#!/bin/sh

set -e -x

# set up the toolchain dir
mkdir -p toolchains/$TARGET
export TOOLCHAIN=$(pwd)/toolchains/$TARGET

# prepare android ndk toolchain
"$ANDROID_NDK_HOME/build/tools/make-standalone-toolchain.sh" \
  --ndk-dir="$ANDROID_NDK_HOME" \
  --toolchain=$NDK_TOOLCHAIN-clang3.6 \
  --install-dir=$TOOLCHAIN \
  --platform=android-9

# add toolchain to path (along with protobuf)
export PATH="$TOOLCHAIN/bin:$WORKSPACE/protobuf_native/bin:$PATH"
ln -s "$TOOLCHAIN/bin/clang++" "$TOOLCHAIN/bin/clang++-3.6"
ln -s "$TOOLCHAIN/bin/clang" "$TOOLCHAIN/bin/clang-3.6"

# Add java home and java path for jni
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/
export PATH=$JAVA_HOME/bin:$PATH


# remove pthreads from the pgkconfigs (not in android)
for file in toxcore/lib/pkgconfig/*.pc; do
  sed -i "/^prefix=/s|.*|prefix=$TOOLCHAIN/sysroot/usr/|" $file
  sed -i "s|-lpthread||" $file
done

export PKG_CONFIG_PATH="$TOOLCHAIN/sysroot/usr/lib/pkgconfig"

# move precompiled libs to the toolchain
cp -r toxcore/* $TOOLCHAIN/sysroot/usr/


cd tox4j

export SBT="sbt -Dsbt.log.noformat=true"
export ALWAYS_BUILD=tox4j
buildscripts/04_build

# Copy artifacts
cp projects/tox4j/target/cpp/bin/*.so $WORKSPACE/artifacts/
cp projects/tox4j/target/scala-2.11/*.jar $WORKSPACE/artifacts/

# Strip the .so to save space
$TARGET-strip -s $WORKSPACE/artifacts/*.so
