#!/bin/sh

set -e -x

# Add java home and java path for jni
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/
export PATH=$JAVA_HOME/bin:$PATH

buildscripts/02_toolchain

TOOLCHAIN="$PWD/toolchains/$TARGET"

# add toolchain to path (along with protobuf)
export PATH="$TOOLCHAIN/bin:$WORKSPACE/protobuf_native/bin:$PATH"

# move precompiled libs to the toolchain
cp -r toxcore/* $TOOLCHAIN/sysroot/usr/

cd tox4j

export SBT="sbt -Dsbt.log.noformat=true"
buildscripts/04_build

# Copy artifacts
cp projects/tox4j/target/cpp/bin/*.so $WORKSPACE/artifacts/
cp projects/tox4j/target/scala-2.11/*.jar $WORKSPACE/artifacts/

# Strip the .so to save space
$TARGET-strip -s $WORKSPACE/artifacts/*.so
