---
name: ci

on:
  pull_request:
    branches: [master]

# Cancel old builds when pushing new commits.
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  docker:
    strategy:
      matrix:
        target: [jvm]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build toxchat/jvm-toxcore-c:${{ matrix.target }}
        uses: docker/build-push-action@v5
        with:
          file: docker/${{ matrix.target }}.Dockerfile
          tags: toxchat/jvm-toxcore-c:${{ matrix.target }}

  ktlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.49.1/ktlint && chmod a+x ktlint
      - run: ./ktlint
